apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod-namespace
spec:
  selector:
    app: hostober
    tier: backend
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: http