version: '3'
services:
  frontend:
    image: sageiyke/vueapp:v1
    build:
      context: ./
      dockerfile: web.Dockerfile
    container_name: frontend
    # restart: always
    ports:
      - "80:80"
    env_file:
      - .env.vault
    # command: npm run serve

  backend:
    image: sageiyke/flaskapp:v1
    build:
      context: ./
      dockerfile: api.Dockerfile
    ports:
      - "5000:5000"
    container_name: backend
    # restart: always
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    env_file:
      - .env.vault
    # command: flask run --host=0.0.0.0