version: '3'
services:
  frontend:
    image: frontend:latest
    ports:
      - "8080:8080"
    env_file:
      - .env

  backend:
    image: backend:latest
    ports:
      - "5080:5080"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    env_file:
      - .env